---
output:
  pdf_document: 
    toc: yes
    number_sections: yes
  html_document: default
editor_options:
  chunk_output_type: console
---
# Measurements

## Ecophysiology trait measurement 

### Import data

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(readxl)
library(ggplot2)
SoftTraits <- read_excel("Natura_data/DRYER_infocollect_morpho.xlsx", 
  
                         
                         
      col_types = c("skip", "skip", "numeric", 
        "skip", "text", "text", "skip", "skip", 
        "text", "text", "skip", "skip", "skip", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", "numeric",
        "skip", "skip", "skip"))

SoftTraits <- SoftTraits %>%
  mutate(Genus = case_when(
    Species == 'falcata' ~ 'Eperua',
    Species == 'hostmannii' ~ 'Iryanthera',
    Species == 'copaia' ~ 'Jacaranda',
    Species == 'officinalis' ~ 'Pterocarpus',
    Species == 'globulifera' ~ 'Symphonia',
    Species == 'melinonii' ~ 'Tachigali',
    Species == 'surinamensis' ~ 'Virola',
    TRUE ~ Genus)
  )

SoftTraits$name <- paste(SoftTraits$Genus, SoftTraits$Species)


```
### Leaf thickness

```{r}
ggplot(SoftTraits) +
  aes(x = name, y = MeanLeafThickness, fill = name) +
  geom_boxplot(shape = "circle") +
  scale_x_discrete(guide = guide_axis(angle = 30)) +
  scale_fill_hue(direction = 1) +
  labs(
    title = "Mean leaf thickness of the seedlings",
    subtitle = " in natura",
    x = "Species",
    y = "Mean leaf thickness (mm)" ) +
  theme_minimal() +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(
      face = "italic",
      hjust = 0.5
    )
  )
```


### Seedling heights

```{r echo=FALSE}

library(ggplot2)

SoftTraits <- SoftTraits %>%
  mutate(Genus = case_when(
    Species == 'falcata' ~ 'Eperua',
    Species == 'hostmannii' ~ 'Iryanthera',
    Species == 'copaia' ~ 'Jacaranda',
    Species == 'officinalis' ~ 'Pterocarpus',
    Species == 'globulifera' ~ 'Symphonia',
    Species == 'melinonii' ~ 'Tachigali',
    Species == 'surinamensis' ~ 'Virola',
    TRUE ~ Genus)
  )

SoftTraits$name <- paste(SoftTraits$Genus, SoftTraits$Species)

ggplot(SoftTraits) +
  aes(x = name, y = `Height (cm)`, fill = name) +
  geom_boxplot(shape = "circle") +
  scale_x_discrete(guide = guide_axis(angle = 30)) +
  scale_fill_hue(direction = 1) +
  labs(
    title = "Height of the seedlings",
    subtitle = " in natura",
    x = "Species") +
  theme_minimal() +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(
      face = "italic",
      hjust = 0.5
    )
  )


```

### Stem diameter
```{r echo=FALSE}
ggplot(SoftTraits) +
 aes(x = Genus, y = `Stem_diameter (mm)`) +
 geom_boxplot(shape = "circle", fill = "#112446") +
 theme_minimal()
```



### $\pi_{TLP}$

```{r measurePtlp, echo=FALSE, fig.cap="$\\pi_{TLP}$.", message=FALSE, warning=FALSE}
library(ggplot2)
library(ggpubr)

Ptlp <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/15unEUBxCQz_2ekJPEkL6M5C12tjvFJ0P7nb0iLh6Caw/edit#gid=0")

Ptlp$Species_Name[Ptlp$Species_Name == "Epe.fal"] <- "falcata"
Ptlp$Species_Name[Ptlp$Species_Name == "Iry.hos"] <- "hostmannii"
Ptlp$Species_Name[Ptlp$Species_Name == "Jac.cop"] <- "copaia"
Ptlp$Species_Name[Ptlp$Species_Name == "Pte.off"] <- "officinalis"
Ptlp$Species_Name[Ptlp$Species_Name == "Sym.glo"] <- "globulifera"
Ptlp$Species_Name[Ptlp$Species_Name == "Tac.mel"] <- "melinonii"
Ptlp$Species_Name[Ptlp$Species_Name == "Vir.sur"] <- "surinamensis"

Ptlp <- Ptlp %>% mutate(Genus = "")

Ptlp <- Ptlp %>%
  mutate(Genus = case_when(
    Species_Name == 'falcata' ~ 'Eperua',
    Species_Name == 'hostmannii' ~ 'Iryanthera',
    Species_Name == 'copaia' ~ 'Jacaranda',
    Species_Name == 'officinalis' ~ 'Pterocarpus',
    Species_Name == 'globulifera' ~ 'Symphonia',
    Species_Name == 'melinonii' ~ 'Tachigali',
    Species_Name == 'surinamensis' ~ 'Virola',
    TRUE ~ Genus)
  )

Ptlp$name <- paste(Ptlp$Genus, Ptlp$Species_Name)


shapiro.test(Ptlp$Ptlp) # W = 0.96004, p-value = 0.06093 meets the normality assumption.

Ptlp$name <- as.factor(Ptlp$name)

compare_means(Ptlp ~ name, data = Ptlp, method = "t.test", paired = FALSE)

modelPtlp <- lm(Ptlp ~ name, data = Ptlp)
summary(modelPtlp)

ggplot(Ptlp) +
  aes(x = name, y = Ptlp) +
  geom_boxplot(shape = "circle", fill = "#008EFF") +
  facet_wrap(~Species_Name) +
  theme_minimal()

p1 <- ggplot(Ptlp) +
  aes(x = name, y = Ptlp, fill = name) +
  geom_boxplot(shape = "circle") +
  theme_minimal()+ 
  stat_compare_means(method = "anova")+
  stat_compare_means(label = "p.signif", method = "t.test",
                     ref.group = "Eperua falcata") +
  scale_fill_hue(direction = 1) +
  labs(
    title = "Turgor loss point of the seedlings",
    subtitle = " in natura",
    x = "Species",
    y = "Turgor loss point (MPa)" ) +
  theme_minimal() +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(
      face = "italic",
      hjust = 0.5
    )
  )
p1
```

### $\frac{Fv}{Fm} in natura$

```{r FvFm, echo=FALSE, fig.cap="$\\frac{Fv}{Fm}$."}
library(readxl)
FvFm <- read_excel("Natura_data/3_FvFm/DRYER_FvFm.xlsx")
p2 <-ggplot(FvFm) +
  aes(x = spName, y = `FvFm`) +
  geom_boxplot(shape = "circle", fill = "#2BDD1A") +
  theme_minimal()
p2
```

### $RWC$

```{r measureRWC, echo=FALSE, fig.cap="$RWC$.", message=FALSE, warning=FALSE}
library(readxl)
library(dplyr)
library(ggplot2)
RWC <- read_excel("Natura_data/1_RWC/DRYER_RWC.xlsx")

RWC <- mutate(RWC, RWC=((FW-DW)/(SW-DW)*100))
p3 <- ggplot(RWC) +
  aes(x = Species_Name, y = RWC) +
  geom_boxplot(shape = "circle", fill = "#FF8C00") +
  theme_minimal() 
p3

```


### Gmin
#### Leaf area

I used following code in `ImageJ`:

```{bash imageJsoft, eval=F, echo=T}
run("8-bit");
setAutoThreshold("Default");
//run("Threshold...");
setAutoThreshold("Default");
setOption("BlackBackground", false);
run("Convert to Mask", "method=Default background=Light calculate");
run("Analyze Particles...", "size=1000000-Infinity display summarize");
setAutoThreshold("Default dark");


```


```{r echo=FALSE}
LeafArea <- read_excel("Natura_data/2_gmin/LeafAreaFinalResultsDRYERnatura.xlsx", col_types = c("text", "text", "skip",        "numeric", "skip", "skip", "skip", "skip"))
LeafArea

```
 
```{r echo=FALSE}
library(readr)
library(dplyr)
library(ggplot2)

Gmin <- read_csv("Natura_data/2_gmin/Gmin_DRYERwithLA.csv", 
    col_types = cols(idTree = col_skip(), 
        beta = col_skip(), file = col_skip()))
ggplot(Gmin) +
  aes(
    x = specCode,
    y = gmin.slope_function,
    colour = specCode
  ) +
  geom_boxplot(shape = "circle", fill = "#112446") +
  scale_color_brewer(palette = "Accent", direction = 1) +
  coord_flip() +
  theme_minimal()

p4 <- ggplot(Gmin) +
  aes(x = specCode, y = gmin.slope_function) +
  geom_boxplot(shape = "circle", fill = "#FF69B4") +
  theme_minimal()
```

## Root:shoot ratio

to fill


### Summary 
```{r echo=FALSE, message=FALSE, warning=FALSE}

library(ggplot2)
library(cowplot)

plot_grid(p1, p2, p3, p4, labels = c('A', 'B', 'C', 'D'), label_size = 12)

```


## Soil analysis

```{r echo=FALSE}
library(readxl)
library(dplyr)
library(tidyverse)
library(ggplot2)

analyses_sol <- read_excel("C:/Users/marion.boisseaux/Dropbox/Mon PC (Jaboty20)/Documents/DRYER/Soil/analyses_sol.xls", sheet = "Feuil1")

analyses_sol <- analyses_sol %>% mutate(`sable(%)` = `Sables fins(%)` + `Sables grossiers(%)` , `limon(%)` = `Limons fins(%)` + `Limons grossiers(%)`)

sample <- c(rep("Greenhouse" , 3) , rep("Paracou" , 3))
soil_type <- rep(c("sable" , "limon" , "argile") , 2)
value <- c(85.3,7.7,7,83.2,7.1,9.7)
data <- data.frame(sample,soil_type,value)
 
# Stacked

ggplot(data, aes(fill=soil_type, y=value, x=sample)) + 
    geom_bar(position="fill", stat="identity")


library(ggplot2)

ggplot(analyses_sol) +
 aes(x = `Code Echantillon`, weight = `P-PO4(mg/kg)`) +
 geom_bar(fill = "#BF7C2A") +
 labs(x = "Echantillon", y = "P-PO4 (mg/kg)", title = "Phosphore assimilable ", subtitle = "(Olsen)") +
 theme_minimal()


```

## Microbial analyses

Weights of samples before sterilization. 
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(readxl)
Microbio <- read_excel("Natura_data/7_Microbio/Microbio.xlsx")
Microbio
```




