# Traits


This chapter defines measured traits, the organization of the measurements with the associated protocols.

## Soft traits

* **LA**: leaf area $cm^{2}$
* **LDMC**: leaf dry matter content $g.g^{-1}$
* **LT**: leaf thickness ($\mu m$)
* **SLA**: specific leaf area ($g.cm^{-2}$)
* Plant height ($cm$)
* Stem diameter ($cm$)
* Number of leaves 

  + Notes on Number of leaves : 
  + NbLeaves	includes NbLeaves_dead but not NbLeaves_Future
  + NbLeaves_dead included in Nb_Leaves
  + NbLeaves_Future	not included in NbLeaves
  + elastique toujours avec feuilles du haut 
  + sur feuille manuscrite : noté feuilles bas + feuilles haut pour les ef, ih, jc, po (T101)

* Number of leaflets : for compound leaves.
* **SRL**: Specific root length ($m.g^{-1}$)
* Root to shoot ratio 
* total biomass 
* Wilting stage* : D0 non-wilted leaf, D1 slightly wilted, D2 wilted, and D3 severly wilted.

## Hydraulic traits

* **RWC**: relative water content (%) is of special interest as it reflects the amount of water present the leaf relative to the maximum it can hold (*INSERER BIBLIO Barrs & Weatherley 1962*)
* **$\pi_{TLP}$**: leaf water potential at which leaf cells lose turgor (MPa), a key drought tolerance trait. 
* **$\phi_{midday}$** : midday leaf water potential (MPa). A measure affected by any cuticular or stomatal transpiration and, thus, broadly captures the integrated effects of plant traits and the environment on the minimum water potential a plant reaches (Giles et al, 2020).
* **$g_{min}$**: leaf minimum conductance $mmol.m^{-2}.s^{-1}$ taking into account water losses through the cuticle and incompletely closed stomata.
* **Stomatal characteristics (size, density)**: morphological characteristic at the crossroads between water loss and the maximum rate of photosynthesis.(*INSERER BIBLIO Julio V. Schneider 2016*)
* **Nervation density**: determining the capacity of water supply in leaves. (*INSERER BIBLIO Julio V. Schneider 2016*)
* Leaf chemistry : To assess the leaves' concentration in carbon, nitrogen and phosphorous.

## Photochemical trait
 
* **$\frac{Fv}{Fm}$**: maximum quantum yield of photosystem II, which reflects photosynthesis efficiency ($\mu mol . m^{-2} . s^{-1}/ \mu mol . m^{-2} . s^{-1}$). It is an indicator of photosynthetic performance, as it has been shown to be sensitive to drought constraints in tropical forests (*INSERER BIBLIO Manzi et al 2021*) but decline after other leaf hydraulic traits (*INSERER BIBLIO Trueba et al 2019*).
* **Chlorophyll content**: 
* **$A_{sat}$**: 

## Microbial analyses : bacteria + fungi leaf and root endophytes

* Leaf and root surface-sterilization, storage -20°C 
* Leaf and root DNA extraction (high-throughput sequencing of amplicons)
* PCR with tagged primers and sequencing performing with illumina miSeq and paired technology to obtain reads: Since fungi were shown to be more tolerant than bacteria to water stress (*INSERER BIBLIO Preece 2019*) we will then focus on fungi and in the leaves to unveil any potential corrolations with the leaves' measured traits.
* Use of OBITools + metabaR packages (pair-end assembly, read assignment, read dereplication, taxonomic assignment, chimera detection, sequence clustering)
* Goal: relate MOTUs to taxonomic names and search for functional guilds.

        



## Protocols

* [**$\pi_{TLP}$** protocol](../3_Protocol/Protocole_Ptlp.pdf)
* [**RWC** protocol](../3_Protocol/RWC_Boisseaux.docx)
* [**Stomata** protocol](../3_Protocol/Analyse Stomates_Marion.docx)
* [**FvFm** protocol](../3_Protocol/Fluo_Bellifa.docx)
* [**gmin** protocol](../3_Protocol/Gmin protocol.docx)
* [**leaf venation** protocol](../3_Protocol/ProtocolLeafVeins_MB_2.docx) 
* [**Surface-sterilization for isolation of endophytes** protocol](../3_Protocol/Sterilisation.docx)

