c# Results

#Library

```{r}

library(dplyr)
library(readxl)
library(googlesheets)
library(googledrive)


```


# Height / Diameter / Leaves

```{r Combining_DHLdata, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}

#t0

DHLT0 <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1bB-baD-dJS4iMqVv6nR0vhfv5SgRFJj6gkLvJc7UXU0/edit#gid=598092754", range = "Indv") %>% select(-Remarques, -BatchNbr) %>% 
  mutate(Time='t0')
  
  
  
#t21
DHLT21 <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1mwfDSZfJdRcFRU2UmeeVz3dxjHiAcvgKiMzvaNgKCjI/edit#gid=858865895", range = "Sheet1") %>% select(-RemarquesT21, -BatchNbr) %>% 
  mutate(Time='t21')

#t27

DHLT27 <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/10ubQDESSYhJHhHpMQ_XoIxR9xYQWfO54qitU7ddGz9A/edit#gid=770489906", range = "Indv") %>% select(-T27_Remarques, -BatchNbr) %>% 
  mutate(Time='t27')

#T51
DHLT51 <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1MCTMj4Zw9CHYj_pYPgUh65ileKenQVvqCuxiEejSX5E/edit#gid=0", range = "Sheet1") %>% select(-RemarquesT51) %>% 
  mutate(Time= 't51')


#T57
DHLT57 <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1btxFeXLK0j8gFA4WRvI0xNqO8211kid371neY7Qj2AM/edit#gid=0", range = "Sheet1")

DHLT57 <- DHLT57 %>% 
  select(UniqueCode, Block, Sblock, Treatment, Species, T57_Height, T57_Diameter, T57_Nb_leaves, T57_Nb_dead_leaves, T57_Nb_future_leaves)%>%
  mutate(Time= 't57') %>%
  relocate(Time, .before= UniqueCode)

DHLT57$T57_Nb_dead_leaves<- as.numeric(unlist(DHLT57$T57_Nb_dead_leaves))

DHLT57 <- DHLT57 %>% 
  rename(Height = T57_Height, Diameter = T57_Diameter, NbLeaves_Total = T57_Nb_leaves, NbLeaves_dead =T57_Nb_dead_leaves, NbLeaves_Future = T57_Nb_future_leaves)

#T71 

DHLT71 <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1i12T_C68Bvss05J3-LlWAQmNnytbdQ_r60SQ3I-eLa0/edit#gid=0", range = "Sheet1")

DHLT71 <- DHLT71 %>% 
  select(UniqueCode, Block, Sblock, Treatment, Species, T71_Height, T71_Diameter, T71_NbLeaves_Under, T71_NbLeaves_Above, T71_NbLeaves_Total, T71_Nb_dead_leaves, T71_Nb_future_leaves)%>%
  mutate(Time= 't71') %>%
  relocate(Time, .before= UniqueCode)

DHLT71$T71_Height <- as.numeric(unlist(DHLT71$T71_Height))

DHLT71 <- DHLT71 %>% 
  rename(Height = T71_Height, Diameter = T71_Diameter, NbLeaves_Under = T71_NbLeaves_Under, NbLeaves_Above= T71_NbLeaves_Above, NbLeaves_Total = T71_NbLeaves_Total, NbLeaves_dead = T71_Nb_dead_leaves, NbLeaves_Future = T71_Nb_future_leaves)

#T101

DHLT101 <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1gpMeECaLhuP9frbeMGvr1PjerB-2THzKJvoPUlFfLm4/edit#gid=0", range = "dhlt101") %>% select(-comment_T101)

DHLT101$NbLeaves_Future <- as.numeric(DHLT101$NbLeaves_Future)

#merge
DataDHL <- bind_rows(DHLT0, DHLT21, DHLT27, DHLT51, DHLT57, DHLT71, DHLT101)

gs_auth()

data(DataDHL)

googledrive::drive_create("DataDHL", path = "~/These/DRYERgreenhouse/Height", type = "spreadsheet")

## Direct storage
# Create an empty spreadsheet. It is stored as an object with a sheet_id and drive_id 
ss <- googledrive::drive_create("DataDHL", path = "~/These/DRYERgreenhouse/Height", type = "spreadsheet")

# Put the data.frame in the spreadsheet and provide the sheet_id so it can be found
googlesheets4::sheet_write(data = DataDHL, ss = ss, sheet = "Sheet1")

```

# Wilting stages

Link to indesign document

#DHL graphs

## height graph
```{r Heightgraphs}
DHL <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1qUIORsjMQW_fb-Bd2Ts8lTHzHA1N7hSWlAZ97Mdv9aw/edit#gid=0", range = "Sheet1")

#resistance + reislience T21 + T51

DHL %>%
 filter(Time %in% c("t21", "t51")) %>%
 ggplot() +
  aes(x = Time, y = Height, fill = Treatment) +
  geom_boxplot(shape = "circle") +
  scale_fill_manual(
    values = list(
      C0 = "#0817FE",
      D1 = "#7ACE72"
    )
  ) +
  labs(title = "Height") +
  theme_minimal() +
  facet_wrap(vars(Species))

#resistance + reislience T27 + T57

DHL %>%
 filter(Time %in% c("t27", "t57")) %>%
 ggplot() +
  aes(x = Time, y = Height, fill = Treatment) +
  geom_boxplot(shape = "circle") +
  scale_fill_manual(
    values = list(
      C0 = "#0817FE",
      D2 = "#fafafa"
    )
  ) +
  labs(title = "Height") +
  theme_minimal() +
  facet_wrap(vars(Species))

#resistance + reislience T71 + T101

DHL %>%
 filter(Time %in% c("t71", "t101")) %>% 
  mutate(Time = factor(Time, levels=c("t71", "t101"))) %>%
 ggplot() +
  aes(x = Time, y = Height, fill = Treatment) +
  geom_boxplot(shape = "circle") +
  scale_fill_manual(
    values = list(
      C0 = "#0817FE",
      D3 = "#f59b42"
    )
  ) +
  labs(title = "Height") +
  theme_minimal() +
  facet_wrap(vars(Species))

#resistance
DHL %>%
 filter(Time %in% c("t0", "t21", "t27", "t71")) %>% 
 ggplot() +
  aes(x = Time, y = Height, fill = Treatment) +
  geom_boxplot(shape = "circle") +
  scale_fill_manual(
    values = list(
      C0 = "#0817FE",
      D1 = "#7ACE72",
      D2 = "#fafafa",
      D3 = "#f59b42"
    )
  ) +
  labs(title = "Height") +
  theme_minimal() +
  facet_wrap(vars(Species))
```

##diameter graphs
```{r Diameter}
DHL <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1qUIORsjMQW_fb-Bd2Ts8lTHzHA1N7hSWlAZ97Mdv9aw/edit#gid=0", range = "Sheet1")

#resistance + reislience T21 + T51

DHL %>%
 filter(Time %in% c("t21", "t51")) %>%
 ggplot() +
  aes(x = Time, y = Diameter, fill = Treatment) +
  geom_boxplot(shape = "circle") +
  scale_fill_manual(
    values = list(
      C0 = "#0817FE",
      D1 = "#7ACE72"
    )
  ) +
  labs(title = "Diameter") +
  theme_minimal() +
  facet_wrap(vars(Species))

#resistance + reislience T27 + T57

DHL %>%
 filter(Time %in% c("t27", "t57")) %>%
 ggplot() +
  aes(x = Time, y = Diameter, fill = Treatment) +
  geom_boxplot(shape = "circle") +
  scale_fill_manual(
    values = list(
      C0 = "#0817FE",
      D2 = "#fafafa"
    )
  ) +
  labs(title = "Diameter") +
  theme_minimal() +
  facet_wrap(vars(Species))

#resistance + reislience T71 + T101

DHL %>%
 filter(Time %in% c("t71", "t101")) %>% 
  mutate(Time = factor(Time, levels=c("t71", "t101"))) %>%
 ggplot() +
  aes(x = Time, y = Diameter, fill = Treatment) +
  geom_boxplot(shape = "circle") +
  scale_fill_manual(
    values = list(
      C0 = "#0817FE",
      D3 = "#f59b42"
    )
  ) +
  labs(title = "Diameter") +
  theme_minimal() +
  facet_wrap(vars(Species))

#resistance
DHL %>%
 filter(Time %in% c("t0", "t21", "t27", "t71")) %>% 
 ggplot() +
  aes(x = Time, y = Diameter, fill = Treatment) +
  geom_boxplot(shape = "circle") +
  scale_fill_manual(
    values = list(
      C0 = "#0817FE",
      D1 = "#7ACE72",
      D2 = "#fafafa",
      D3 = "#f59b42"
    )
  ) +
  labs(title = "Height") +
  theme_minimal() +
  facet_wrap(vars(Species))
```

# stomatal conductance gs

```{r intermediate_gs}
#intermediate gs

t8 <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1FaJTPoIdiUYW0xuebZsOPCclcZOxSZy6STZRLpl75VI/edit#gid=2004401054", range = "gs sem 02/11") %>% select(-DateColl, -Height, -Diameter, -Nb_leaves, -comment)

t14 <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1FaJTPoIdiUYW0xuebZsOPCclcZOxSZy6STZRLpl75VI/edit#gid=2004401054", range = "gs sem 08/11") %>% select(-DateColl, -Height, -Diameter, -Nb_leaves, -comment)

#merge
intermediate_gs <- bind_rows(t8, t14) 

```



# Non Destructive 

```{r message=FALSE, warning=FALSE, include=FALSE}

library(dplyr)

T0_NONdestructive <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1hxXws0kkgQhkC3T023X6QZw5o-RAjnNo8c3_KcWfTpw/edit#gid=799954127", range = "non_destructif")

T0_NONdestructive <- subset(T0_NONdestructive, select = Time:WUE)

T21_NONdestructive <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1Vkmx3XCVR4L0QG22b_-zcIFutezT59gUlmr1ALW4V2Y/edit#gid=258591157",range = "non_destructif")

T21_NONdestructive <- subset(T21_NONdestructive, select = Time:WUE)
 
T27_NONdestructive <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1SQekhd-T9yTKDTILUuHF0NY3Nlggy4enzFhSXLxJlK0/edit#gid=822184942",range = "non_destructif")

T27_NONdestructive <- subset(T27_NONdestructive, select = Time:WUE)

T51_NONdestructive<- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1lmgpcbXdVcC2de3_-uc3g0w_P8Ab7z1m4faLhd2EmXI/edit#gid=539250691", range = "non_destructif")

T51_NONdestructive <- subset(T51_NONdestructive, select = Time:WUE)

T57_NONdestructive<- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1rh34QE6izuGEnB4eQFLn4lv5oEf2CaFscT1Tsjc6NQA/edit#gid=822184942", range = "non_destructif")

T57_NONdestructive <- subset(T57_NONdestructive, select = Time:WUE)

T71_NONdestructive <- 
googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1al3U5pv2FQ0dWF6sbroB_6kJdzW1OnaLVpohykcKx7c/edit#gid=258591157", range = "non_destructif")

T71_NONdestructive <- subset(T71_NONdestructive, select = Time:WUE)

T101_NONdestructif <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1ItJdPwjk5uwm6xcuP79dnaRvxP88lwVACGWBStx0NvI/edit#gid=0", range = "non_destructif")

T101_NONdestructif <- subset(T101_NONdestructif, select = Time:WUE)


Data_NonDes <- bind_rows(T0_NONdestructive,T21_NONdestructive,T27_NONdestructive, T51_NONdestructive, T57_NONdestructive, T71_NONdestructive, T101_NONdestructif)

Data_NonDes_essai <- bind_rows(Data_NonDes, intermediate_gs)

gs_auth()


## Direct storage
# Create an empty spreadsheet. It is stored as an object with a sheet_id and drive_id 
ss <- googledrive::drive_create("Traits", path = "~/These/DRYERgreenhouse/", type = "spreadsheet")

# Put the data.frame in the spreadsheet and provide the sheet_id so it can be found
googlesheets4::sheet_write(data = Data_NonDes_essai, ss = ss, sheet = "Sheet1")

library(rio)
#export(Data, "datagreenhouse.csv")


```



## $\frac{Fv}{Fm}$

```{r measureFvFm, echo=FALSE, fig.cap="$\\frac{Fv}{Fm}$.", message=FALSE, warning=TRUE}
ggplot(Data_NonDes) +
  aes(x = Time, y = FvFm, fill = Treatment) +
  geom_boxplot(shape = "circle") +
 labs(title = "FvFm") +
  scale_fill_manual(
    values = list(
      C0 = "#4064CB",
      D1 = "#31B425",
      D2 = "#ECE320",
      D3 = "#FF7961"
    )
  ) +
  theme_minimal() +
  facet_wrap(vars(Species), scales = "free")


```

## Asat
```{r echo=FALSE, message=FALSE, warning=TRUE}
A <- ggplot(Data_NonDes) +
  aes(x = Time, y = Asat, fill = Treatment) +
  geom_boxplot(shape = "circle") +
 labs(title = "Carbon assimilation (µmolCO2.m².s-1)") +
  scale_fill_manual(
    values = list(
      C0 = "#6D90F8",
      D1 = "#63E31D",
      D2 = "#ECE320",
      D3 = "#FF7961"
    )
  ) +
  theme_minimal() +
  facet_wrap(vars(Species), scales = "free")

plot(A)
```


## E 
```{r echo=FALSE}
ggplot(Data_NonDes) +
  aes(x = Time, y = E, fill = Treatment) +
  geom_boxplot(shape = "circle") +
 labs(title = "Evapotranspiration") +
  scale_fill_manual(
    values = list(
      C0 = "#6D90F8",
      D1 = "#63E31D",
      D2 = "#ECE320",
      D3 = "#FF7961"
    )
  ) +
  theme_minimal() +
  facet_wrap(vars(Species), scales = "free")
```

## WUE
```{r echo=FALSE}
ggplot(Data_NonDes) +
  aes(x = Time, y = WUE, fill = Treatment) +
  geom_boxplot(shape = "circle") +
 labs(title = "Water use efficiency (µmolCO2.mmolH2O)") +
  scale_fill_manual(
    values = list(
      C0 = "#6D90F8",
      D1 = "#63E31D",
      D2 = "#ECE320",
      D3 = "#FF7961"
    )
  ) +
  theme_minimal() +
  facet_wrap(vars(Species), scales = "free")
```

## gs

```{r echo=FALSE}
#rajouter les gs fait entre t0 et j21
ggplot(Data_NonDes) +
  aes(x = Time, y = gs, fill = Treatment) +
  geom_boxplot(shape = "circle") +
 labs(title = "Stomatal conductance (mmolH2O.m².s-1)") +
  scale_fill_manual(
    values = list(
      C0 = "#6D90F8",
      D1 = "#63E31D",
      D2 = "#ECE320",
      D3 = "#FF7961"
    )
  ) +
  theme_minimal() +
  facet_wrap(vars(Species), scales = "free")
```


# Destructive


```{r include=FALSE}
library(dplyr)

T0_destructive <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1hxXws0kkgQhkC3T023X6QZw5o-RAjnNo8c3_KcWfTpw/edit#gid=799954127", range = "destructif")

T0_destructive <- T0_destructive[1:14]

T21_destructive <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1Vkmx3XCVR4L0QG22b_-zcIFutezT59gUlmr1ALW4V2Y/edit#gid=258591157",range = "destructif")

T21_destructive <- select(T21_destructive, select = -c(14:18))
T21_destructive <- T21_destructive[1:14]
 
T27_destructive <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1SQekhd-T9yTKDTILUuHF0NY3Nlggy4enzFhSXLxJlK0/edit#gid=822184942",range = "destructif")

T27_destructive <- T27_destructive[1:19]

T51_destructive<- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1lmgpcbXdVcC2de3_-uc3g0w_P8Ab7z1m4faLhd2EmXI/edit#gid=539250691", range = "destructif")

T51_destructive <- T51_destructive[1:16]

T57_destructive<- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1rh34QE6izuGEnB4eQFLn4lv5oEf2CaFscT1Tsjc6NQA/edit#gid=822184942", range = "destructif")

T57_destructive <- T57_destructive[1:16]

T71_destructive <- 
googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1al3U5pv2FQ0dWF6sbroB_6kJdzW1OnaLVpohykcKx7c/edit#gid=258591157", range = "destructif")

T71_destructive <- T71_destructive[1:16]


DataDes <- bind_rows(T0_destructive,T21_destructive,T27_destructive, T51_destructive, T57_destructive, T71_destructive)

```
## RWC


The relative water content (RWC; %) was calculated as (fresh weight - dry weight) / (turgid weight - dry weight) * 100.

```{r}
DataDes <- DataDes %>% mutate(RWC = (RWC_FW- RWC_DW)/(RWC_SW - RWC_DW)*100)



library(ggplot2)

ggplot(DataDes) +
 aes(x = Time, y = RWC, fill = Treatment) +
 geom_boxplot(shape = "circle") +
 scale_fill_manual(values = list(
 C0 = "#6D91F8", D1 = "#25C100", D2 = "#C2B8BE",  D3 = "#FF7961")) +
 theme_minimal() +
   facet_wrap(vars(Species))
```


## Leaf thickness
```{r}


```



##Leaf surface
## Root to shoot ratio 


